// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqa8pV7AC7KbKdkLZwBHmoUPMZ3T75rHk',
    appId: '1:124116953140:android:00c5b420a91b2cff5e4261',
    messagingSenderId: '124116953140',
    projectId: 'ca-hubb',
    databaseURL: 'https://ca-hubb-default-rtdb.firebaseio.com',
    storageBucket: 'ca-hubb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt6UEpn55wyFwHUPNVjdR-D64J9WFW7_U',
    appId: '1:124116953140:ios:25f3b9243c4b13515e4261',
    messagingSenderId: '124116953140',
    projectId: 'ca-hubb',
    databaseURL: 'https://ca-hubb-default-rtdb.firebaseio.com',
    storageBucket: 'ca-hubb.firebasestorage.app',
    androidClientId: '124116953140-bijekbh7ksrlid7bk3rocl4c9dracfd0.apps.googleusercontent.com',
    iosClientId: '124116953140-j45eoqgu6hr847v2n8hp7invmiiodtdu.apps.googleusercontent.com',
    iosBundleId: 'com.cahubb.pakistan',
  );

}